// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_rXwX9jtfNR1sSzMhn-WCShGFGS453m0',
    appId: '1:963730494362:web:aa8c5ecbb5e4e356fda023',
    messagingSenderId: '963730494362',
    projectId: 'my-first-hp1910',
    authDomain: 'my-first-hp1910.firebaseapp.com',
    storageBucket: 'my-first-hp1910.firebasestorage.app',
    measurementId: 'G-JC6RG78GC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_V7TAmH4dsNKC4zsjMjBkfbwj-w9yoA',
    appId: '1:963730494362:android:3c5004bcd526ee7cfda023',
    messagingSenderId: '963730494362',
    projectId: 'my-first-hp1910',
    storageBucket: 'my-first-hp1910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bxvHynjv2YY-Wh_zX3jQA7lZUO2D_tw',
    appId: '1:963730494362:ios:bef90d1c8749121afda023',
    messagingSenderId: '963730494362',
    projectId: 'my-first-hp1910',
    storageBucket: 'my-first-hp1910.firebasestorage.app',
    iosBundleId: 'com.hp.sanman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0bxvHynjv2YY-Wh_zX3jQA7lZUO2D_tw',
    appId: '1:963730494362:ios:bef90d1c8749121afda023',
    messagingSenderId: '963730494362',
    projectId: 'my-first-hp1910',
    storageBucket: 'my-first-hp1910.firebasestorage.app',
    iosBundleId: 'com.hp.sanman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_rXwX9jtfNR1sSzMhn-WCShGFGS453m0',
    appId: '1:963730494362:web:cddd193b2e1efef9fda023',
    messagingSenderId: '963730494362',
    projectId: 'my-first-hp1910',
    authDomain: 'my-first-hp1910.firebaseapp.com',
    storageBucket: 'my-first-hp1910.firebasestorage.app',
    measurementId: 'G-C9G5JXYWTT',
  );
}
